/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 6d12c2e3ac852f0c9c1e9f67cb677fc5)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: "https://2klips.github.io" | "http://127.0.0.1:5173,http://localhost:5173";
	OPENAI_TRANSCRIBE_MODEL: "gpt-transcribe";
	ENABLE_OPENAI_STT_MODEL_SELECTOR: "true";
	GEMINI_TRANSCRIBE_MODEL: "gemini-2.5-flash";
	LLM_PROVIDER: "openai" | "gemini";
	OPENAI_LLM_MODEL?: "gpt-5.6-luna";
	GEMINI_LLM_MODEL: "gemini-3.1-flash-lite";
	OPENAI_API_KEY: string;
	GEMINI_API_KEY?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface QaEnv {
		ALLOWED_ORIGINS: "https://2klips.github.io";
		OPENAI_TRANSCRIBE_MODEL: "gpt-transcribe";
		ENABLE_OPENAI_STT_MODEL_SELECTOR: "true";
		GEMINI_TRANSCRIBE_MODEL: "gemini-2.5-flash";
		LLM_PROVIDER: "openai";
		OPENAI_LLM_MODEL: "gpt-5.6-luna";
		GEMINI_LLM_MODEL: "gemini-3.1-flash-lite";
		OPENAI_API_KEY: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
