/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 7e18e30dd88e738ffc3bb53411214c3f)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: "http://127.0.0.1:5173,http://localhost:5173";
	OPENAI_TRANSCRIBE_MODEL: "gpt-transcribe";
	GEMINI_TRANSCRIBE_MODEL: "gemini-2.5-flash";
	GEMINI_LLM_MODEL: "gemini-3.1-flash-lite";
	OPENAI_API_KEY: string;
	GEMINI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
